### PR TITLE
Switch docker login to --password-stdin

### PR DESCRIPTION
**Pull request by NiklasMerz**
This is my attempt to use a more secure approach to pass password for CI environments

See #20 and https://stackoverflow.com/questions/51489359/docker-using-password-via-the-cli-is-insecure-use-password-stdin

### CODE REVIEW

**Comment by peter-evans** [comment]
Looks like this would fix #16 too.

**Comment by parkr** [comment]
I’m not sure ENTRYPOINT supports pipe. Could you give this a try and confirm that it works?

**Comment by NiklasMerz** [comment]
I use this in one of my workflows and it works. You could test it again before merging just to make sure :)

**Comment by peter-evans** [comment]
Here is the log of a quick test. I masked my actual username and password.
```
$ docker build -t docker-login .
Sending build context to Docker daemon  20.48kB
Step 1/10 : FROM docker:stable
stable: Pulling from library/docker
921b31ab772b: Already exists 
2d3896533852: Pull complete 
28c34ce20860: Pull complete 
60e67eb6f87f: Pull complete 
c89755d2d247: Pull complete 
73ad5256e0b2: Pull complete 
Digest: sha256:38874a2f8d1c33b51b7e2c629630f54ec32f1fe4aed91133db9da771029e2947
Status: Downloaded newer image for docker:stable
 ---> b4b6dd807869
Step 2/10 : LABEL "name"="Docker Login Action"
 ---> Running in c75c90be3fab
Removing intermediate container c75c90be3fab
 ---> 69d678634149
Step 3/10 : LABEL "maintainer"="GitHub Actions <support+actions@github.com>"
 ---> Running in 43fe4b43a729
Removing intermediate container 43fe4b43a729
 ---> 73b5932b425e
Step 4/10 : LABEL "version"="1.0.0"
 ---> Running in b2263cab5e8c
Removing intermediate container b2263cab5e8c
 ---> b455f1b48a67
Step 5/10 : LABEL "com.github.actions.icon"="log-in"
 ---> Running in 62471117024d
Removing intermediate container 62471117024d
 ---> a943ef81a441
Step 6/10 : LABEL "com.github.actions.color"="blue"
 ---> Running in 7c15418fc6e6
Removing intermediate container 7c15418fc6e6
 ---> 91581a2c5d27
Step 7/10 : LABEL "com.github.actions.name"="Docker Registry"
 ---> Running in f8e44a4cae15
Removing intermediate container f8e44a4cae15
 ---> a26f936e2325
Step 8/10 : LABEL "com.github.actions.description"="This is an Action to log into docker."
 ---> Running in 9420a26892d0
Removing intermediate container 9420a26892d0
 ---> 8344254533db
Step 9/10 : COPY LICENSE README.md THIRD_PARTY_NOTICE.md /
 ---> 08ff3ba64af7
Step 10/10 : ENTRYPOINT echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_URL -u $DOCKER_USERNAME --password-stdin
 ---> Running in 6c2e96f2270a
Removing intermediate container 6c2e96f2270a
 ---> 070b66ebf946
Successfully built 070b66ebf946
Successfully tagged docker-login:latest
```
```
$ docker run \
  -e DOCKER_USERNAME='xxx' \
  -e DOCKER_PASSWORD='xxx' \
  docker-login
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

**Pull request merged**
